apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-app
  labels:
    app: cloud-config-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-app
  template:
    metadata:
      labels:
        app: cloud-config-app
    spec:
      containers:
        - name: cloud-config-app
          image: protap/com-cloud-config:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9296

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-svc
spec:
  ports:
    - port: 80
      targetPort: 9296
  selector:
    app: cloud-config-app
