apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client-app
  labels:
    app: proxy-client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client-app
  template:
    metadata:
      labels:
        app: proxy-client-app
    spec:
      containers:
        - name: proxy-client-app
          image: protap/com-proxy-client:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8900

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client-svc
spec:
  ports:
    - targetPort: 8900
      port: 80
  selector:
    app: proxy-client-app
